### ISSUE TITLE
[FIX] Game Details

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [jeong-hyeonHwang/AGUAGU#11]
## 문제 상황
*어떤 문제가 발생했나요?*
- Camera Permission 관련 String 수정
- 게임 밸런스 테스트용 -> 배포용으로 수정
- Code Archive.swift 삭제

## 반영 형태 및 SEQUENCE
*어떤 식으로 반영할 것인지, 어떤 과정을 거쳐서 해결할건지*

## TODO
- [x] Branch 파기
- [x] Camera Permission 관련 String 수정
- [x] 게임 밸런스 테스트용 -> 배포용으로 수정
- [x] Code Archive.swift 삭제
