### ISSUE TITLE
[FEAT] Insert BGM & SFX Manager

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [jeong-hyeonHwang/AGUAGU#19]
## 문제 상황
*어떤 문제가 발생했나요?*
- AGUAGU에 맞는 배경음악과 사운드 효과의 부재
-> 단, 이러한 사운드들이 게임 몰입에 도움이 되는지에 대해서는 관찰이 필요함

## 반영 형태 및 SEQUENCE
*어떤 식으로 반영할 것인지, 어떤 과정을 거쳐서 해결할건지*
- 케이스는 총 4가지

|BGM|SFX|
|:---:|:---:|
|O|O|
|O|X|
|X|O|
|X|X|

- 어떤 형태가 가장 유효할지 각각의 케이스에 대해 테스트를 통해 반영여부 결정
- BGM 작성
- SFX 작성
- BGM Player 작성
- SFX Player 작성

## TODO
- [x] BGM 작성
- [x]  SFX 작성
- [x] BGM Player 작성
- [x] SFX Player 작성
- [x] 어떤 형태가 가장 유효할지 각각의 케이스에 대해 테스트를 통해 반영여부 결정
-> 이와 관련된 사항은 추후 새로운 이슈 만들기 (유효성 판별 UT용 이슈)

**Comment by jeong-hyeonHwang** [comment]
## 결론

### BGM & SFX 유효성 측면
- 개발자 본인의 시각에서 이루어진 BGM & SFX 유효성 테스트이기 때문에 좀 더 유의미한 정보는 UT를 통해서 얻을 필요성을 느낌
- 만약 BGM과 SFX를 ON/OFF 옵션을 제공하지 않는다면 UT를 거쳐서 네 가지 케이스 중에서 하나를 채택할 예정

### 무드 일치 측면
- BGM과 SFX의 분위기가 게임의 무드와 일치하는지도 UT를 통해 좀 더 알아볼 예정

**Comment by jeong-hyeonHwang** [comment]
### 본 이슈는 BGM & SFX Manager Class 작성을 기점으로 PR이 이루어집니다.
### 위의 결론에서 제기된 추가 검증 사항은 추후 새로운 이슈를 생성해 처리할 예정입니다.
