### ISSUE TITLE
[REFACTOR] Refactor General Codes

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [jeong-hyeonHwang/AGUAGU#27]
## 문제 상황
*어떤 문제가 발생했나요?*
- 전반적인 코드의 퀄리티 상승을 위해 전체 프로젝트에 대한 Refactoring을 진행합니다.

## 반영 형태 및 SEQUENCE
*어떤 식으로 반영할 것인지, 어떤 과정을 거쳐서 해결할건지*
- 코드를 확인하면서 수정 및 제거가 필요하다고 판단되는 사항들에 대해 하나씩 처리합니다.

## TODO
- [x] Branch 파기
- [x] 사용하지 않는`.storyboard` etc 파일 삭제
- [x] 코드베이스로 `SceneDelegate.swift` 수정
- [x] Enum이름 명시적으로 표현되도록 수정하기
- [x] ViewController `addSubview` 관련 코드뷰 축약하기
- [x] Label Setting 관련 메소드 Extension으로 만들기
- [x] 코드 가독성을 해치는 typealias 제거하기
- [x] 분리될 필요가 없다고 판단되는 `Extension`코드 합치기
- [x] 분리될 필요가 있다고 판단되는 `Extension`코드 분리하기
- [x] 불필요한 자세한 Error Message 코드 줄이기
- [x] `SoundManager` 싱글톤 패턴 삭제하기
- [x] `if boolProperty == status` 코드부 `if boolProperty`로 수정
- [x] CGPoint 관련 전역으로 선언된 메소드 CGPoint Extension으로 수정
- [x] UIFont 관련 Extension 추가하기 (labelSetting Method와 밀접한 관련이 있음)
- [x] protocol 폴더 분리하기
- [x] x, y value 관련 struct 만들기
