### ISSUE TITLE
[REFACTOR] General Code Refactor

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [jeong-hyeonHwang/AGUAGU#30]
## 문제 상황
*어떤 문제가 발생했나요?*
- 추가적으로 발생한 수정 가능한 코드에 대한 리팩토링을 진행합니다.
- Thanks to **예니** @yeniful **코인** @Juhwa-Lee1023

## 반영 형태 및 SEQUENCE
*어떤 식으로 반영할 것인지, 어떤 과정을 거쳐서 해결할건지*

## TODO
- [x] Branch 파기
- [ ] `enum HandPoseStatus` CaseIterable 키워드 제거
- [ ] `ViewController.swift`의 `CABasicAnimation` Extension 만들기
- [x] `HandPose+Landmark.swift`의 `drawToContext` 메소드 내부 재사용 프로퍼티 외부로 옮기기
